name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
    - uses: dorny/paths-filter@v3
      id: mainservice-filter
      with:
        filters: |
          runneeded:
            - ./mainservice/*
    - uses: dorny/paths-filter@v3
      id: dateservice-filter
      with:
        filters: |
          runneeded:
            - ./dateservice/*
    - if: steps.mainservice-filter.outputs.runneeded == 'true'
      uses: docker/build-push-action@v5
      with:
        file: mainservice/Dockerfile
        context: ./mainservice
        push: false
        tags: |
          rasmus256docker/cakeotron:${{github.run_number}}
          rasmus256docker/cakeotron:1.0.1

    - if: steps.dateservice-filter.outputs.runneeded == 'true'
      uses: docker/build-push-action@v5
      with:
        file: dateservice/Dockerfile
        context: ./dateservice
        push: false
        tags: |
          rasmus256docker/cakeotron-dateservice:${{github.run_number}}
          rasmus256docker/cakeotron-dateservice:1.0.1
