name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
      id: mainservice-filter
      with:
        filters: |
          runneeded:
            - ./mainservice/*
    - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
      id: dateservice-filter
      with:
        filters: |
          runneeded:
            - ./dateservice/*
    - if: steps.mainservice-filter.outputs.runneeded == 'true'
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        file: mainservice/Dockerfile
        context: ./mainservice
        push: false
        tags: |
          rasmus256docker/cakeotron:${{github.run_number}}
          rasmus256docker/cakeotron:1.0.1

    - if: steps.dateservice-filter.outputs.runneeded == 'true'
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
      with:
        file: dateservice/Dockerfile
        context: ./dateservice
        push: false
        tags: |
          rasmus256docker/cakeotron-dateservice:${{github.run_number}}
          rasmus256docker/cakeotron-dateservice:1.0.1
