name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
    - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
      id: mainservice-filter
      with:
        filters: |
          runneeded:
            - ./mainservice/*
    - uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
      id: dateservice-filter
      with:
        filters: |
          runneeded:
            - ./dateservice/*
    - if: steps.mainservice-filter.outputs.runneeded == 'true'
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
      with:
        file: mainservice/Dockerfile
        context: ./mainservice
        push: false
        tags: |
          rasmus256docker/cakeotron:${{github.run_number}}
          rasmus256docker/cakeotron:1.0.1

    - if: steps.dateservice-filter.outputs.runneeded == 'true'
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
      with:
        file: dateservice/Dockerfile
        context: ./dateservice
        push: false
        tags: |
          rasmus256docker/cakeotron-dateservice:${{github.run_number}}
          rasmus256docker/cakeotron-dateservice:1.0.1
